-- Table structure for table `review`
CREATE TABLE IF NOT EXISTS public.review(
  review_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  review_text text NOT NULL,
  review_date TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  inv_id integer NOT NULL,
  account_id integer NOT NULL
);

-- This will be an optional. Table structure for table 'messages'
CREATE TABLE IF NOT EXISTS public.messages(
  message_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  message_subject character varying(100) NOT NULL,
  message_body text NOT NULL,
  message_created TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  message_to integer NOT NULL,
  message_from integer NOT NULL,
  message_read boolean DEFAULT false NOT NULL,
  message_archived boolean DEFAULT false NOT NULL
);