-- Table structure for table `review`
CREATE TABLE IF NOT EXISTS public.review(
    review_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    review_text text NOT NULL,
    review_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    inv_id integer NOT NULL,
    account_id integer NOT NULL
);

-- Table structure for table 'messages'